-- Chapter 4 reusable ontology layer snippet
USE ROLE SYSADMIN;
USE WAREHOUSE SFE_SAM_SNOWMAN_WH;
USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA SAM_DRIFT;

CREATE OR REPLACE TABLE ONT_CLASS (
  CLASS_NAME STRING,
  PARENT_CLASS STRING,
  IS_ABSTRACT BOOLEAN,
  DESCRIPTION STRING
) COMMENT = 'DEMO: Drift ontology classes (Expires: 2026-05-22)';

CREATE OR REPLACE TABLE ONT_RELATION_DEF (
  RELATION_NAME STRING,
  DOMAIN_CLASS STRING,
  RANGE_CLASS STRING,
  DESCRIPTION STRING
) COMMENT = 'DEMO: Drift ontology relations (Expires: 2026-05-22)';

CREATE OR REPLACE VIEW VW_ONT_PERSON AS
SELECT 'CUSTOMER' AS person_type, CUSTOMER_ID AS person_id, FIRST_NAME, LAST_NAME, COUNTRY
FROM CUSTOMER
UNION ALL
SELECT 'EMPLOYEE' AS person_type, EMPLOYEE_ID AS person_id, FIRST_NAME, LAST_NAME, COUNTRY
FROM EMPLOYEE;
