-- Chapter 9 reusable teardown snippet
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SFE_SAM_SNOWMAN_WH;

DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.SAM_DRIFT.SAM_THE_SNOWMAN;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_SAM_DRIFT_NAIVE;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_SAM_DRIFT_BASE;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_SAM_DRIFT_ONTOLOGY;
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.SAM_DRIFT;
